### PR TITLE
Add script to fix unreserve imbalance by staking orphan request bug

### PR DESCRIPTION
**Pull request by 4meta5**
Commands used to run:
* `./node_modules/.bin/ts-node-transpile-only src/hotfixes/fix-force-unreserve-balance.ts --url wss://moonbeam.kaki.dev`
* `./node_modules/.bin/ts-node src/hotfixes/fix-force-unreserve-balance.ts --network moonbeam`

- [x] print force reserve and unreserve to console
- [x] collect force unreserve (accounts, amounts)
- [x] collect force reserve (accounts, amount)
- [x] sign and send proposal to force unreserve
- [x] limit the number of `forceUnreserve` to 500 per batchCall like in `hotfixes/fix-orphan-request.ts`?

#### (maybe) left todo in follow up
make proposal to force reserve (blocked until staking hotfix extrinsic is added) -- this issue may resolve itself so we will wait a month to see if this occurs...

### CODE REVIEW

**Comment by 4meta5** [comment]
I'm seeing a lot of 
```
Printing accounts with difference between RESERVED and EXPECTED_RESERVED
ACCOUNT:  0x5588204ac5fb53d0a97ba65e2b37ba75a57bd5f1 RESERVED:  1108000000000000000000n EXPECTED RESERVED:  00110800000000000000000000
```
where EXPECTED RESERVED has exactly 2 less trailing zeros than RESERVED and it also has 2 more leading zeros. TODO: verify these cases individually to see if pattern is false positive instance

**Comment by 4meta5** [comment]
So what API endpoint should I use? Is there a list somewhere? As of now I use the commands:
1. `./node_modules/.bin/ts-node src/tools/check-unreserved-balance.ts --network moonbeam`
2. `./node_modules/.bin/ts-node-transpile-only src/tools/check-unreserved-balance.ts --url wss://moonbeam.kaki.dev`

For (1), the output is:
```
(amar-fix-unreserve-imbalance-by-staking-orphan-request-bug)⚡ [1] % ./node_modules/.bin/ts-node src/tools/check-unreserved-balance.ts --network moonbeam
2022-03-20 20:29:59        API/INIT: RPC methods not decorated: eth_feeHistory, moon_isBlockFinalized, moon_isTxFinalized
2022-03-20 20:30:19          API-WS: disconnected from wss://moonbeam.api.onfinality.io/public-ws: 1002:: unexpected reserved bits 0x50
2022-03-20 20:30:19        RPC-CORE: getKeysPaged(key: StorageKey, count: u32, startKey?: StorageKey, at?: BlockHash): Vec<StorageKey>:: disconnected from wss://moonbeam.api.onfinality.io/public-ws: 1002:: unexpected reserved bits 0x50
2022-03-20 20:30:19             DRR: disconnected from wss://moonbeam.api.onfinality.io/public-ws: 1002:: unexpected reserved bits 0x50
2022-03-20 20:30:19        RPC-CORE: health(): Health:: disconnected from wss://moonbeam.api.onfinality.io/public-ws: 1002:: unexpected reserved bits 0x50
(node:7483) UnhandledPromiseRejectionWarning: Error: disconnected from wss://moonbeam.api.onfinality.io/public-ws: 1002:: unexpected reserved bits 0x50
    at W3CWebSocket.value (/Users/4meta5/ong/ps/moonbeam-tools/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/4meta5/ong/ps/moonbeam-tools/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/Users/4meta5/ong/ps/moonbeam-tools/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/Users/4meta5/ong/ps/moonbeam-tools/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:314:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:486:12)
    at WebSocketConnection.handleSocketClose (/Users/4meta5/ong/ps/moonbeam-tools/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at net.js:672:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

For (2), the output is, the request is just hanging...

**Comment by 4meta5** [comment]
Output shows I'm not adding bigints correctly:

```
Printing different RESERVED and EXPECTED_RESERVED for  0x58587e945c161f5c98c20bf2e7eec135f0a5d676
BUG REQUIRES HOTFIX EXTRINSIC TO CORRECT ACCOUNT:  0x58587e945c161f5c98c20bf2e7eec135f0a5d676 RESERVED:  24000580000000000003998n EXPECTED RESERVED:  0010000000000000000000000013898000000000000003998000
INDIVIDUAL DEPOSITS:  [ '010000000000000000000000', '013898000000000000003998', 0n, 0n, 0n ]
```

It is string concatenating the deposits instead of summing them. This is the code that is doing it:
```
const deposits = [
      authorMappingDeposits[accountId] ? authorMappingDeposits[accountId].reserved : 0n,
      candidateDeposits[accountId] ? candidateDeposits[accountId].reserved : 0n,
      delegatorDeposits[accountId] ? delegatorDeposits[accountId].reserved : 0n,
      treasuryDeposits[accountId] ? treasuryDeposits[accountId].reserved : 0n,
      proxyDeposits[accountId] ? proxyDeposits[accountId].reserved : 0n,
    ];
    // expected reserved is sum of deposits
    const expectedReserved: bigint = deposits.reduce((a, b) => a + b, 0n); // this plus is concatenating
```

**Comment by crystalin** [comment]
This is pending https://github.com/polkadot-js/api/issues/4678 to properly query all accounts at the same block height

**Comment by 4meta5** [comment]
This has been moved to moonbeam

**Pull request closed without merging**
